### ISSUE TITLE
project probably needs a license

### ISSUE THREAD

**Issue by midget3111** [DanielWinning/StaticMarkdownBlog#1]
It's a good idea for open source projects to have a license, just so that if your code is used you're still credited for it. Makes your project a bit more creditable as well. There's loads to choose from. I generally go with something GPL based e.g. GPL 3. It allows users to use your code providing their project is open source and under a similar license etc 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by DanielWinning** [comment]
Thanks - I've updated the project to use an MIT licence (for now)
